### ISSUE TITLE
Test01

### ISSUE THREAD

**Issue by vishnuyokzz** [vishnuyokzz/intro-html#8]
# Test01
#7

**Comment by akhilbaiju** [comment]
A pangram is a unique sentence in which every letter of the alphabet is used at least once. The name comes from the Greek root words pan, meaning “all,” and gram, meaning “something written or recorded”. Like any good sentence, good examples of pangrams should contain a subject and a predicate, but the real purpose of a pangram goes beyond its meaning alone.

Because pangrams contain every letter of the alphabet, they are particularly useful to artists who design fonts, as a pangram allows them to display all available letters in a given typeset. Likewise, they are useful for people to practice their handwriting, whether for a child learning cursive or a calligrapher trying a new pen tip. Often they’re used just for fun wordplay.

Pangrams exist in every language, though they may be more or less difficult to construct depending on the language and its unique alphabet.
A pangram is a unique sentence in which every letter of the alphabet is used at least once. The name comes from the Greek root words pan, meaning “all,” and gram, meaning “something written or recorded”. Like any good sentence, good examples of pangrams should contain a subject and a predicate, but the real purpose of a pangram goes beyond its meaning alone.

Because pangrams contain every letter of the alphabet, they are particularly useful to artists who design fonts, as a pangram allows them to display all available letters in a given typeset. Likewise, they are useful for people to practice their handwriting, whether for a child learning cursive or a calligrapher trying a new pen tip. Often they’re used just for fun wordplay.

Pangrams exist in every language, though they may be more or less difficult to construct depending on the language and its unique alphabet.
A pangram is a unique sentence in which every letter of the alphabet is used at least once. The name comes from the Greek root words pan, meaning “all,” and gram, meaning “something written or recorded”. Like any good sentence, good examples of pangrams should contain a subject and a predicate, but the real purpose of a pangram goes beyond its meaning alone.

Because pangrams contain every letter of the alphabet, they are particularly useful to artists who design fonts, as a pangram allows them to display all available letters in a given typeset. Likewise, they are useful for people to practice their handwriting, whether for a child learning cursive or a calligrapher trying a new pen tip. Often they’re used just for fun wordplay.

Pangrams exist in every language, though they may be more or less difficult to construct depending on the language and its unique alphabet.

**Comment by vishnuyokzz** [comment]
Y6
